# Site
repository: sproogen/resume-theme
favicon: images/favicon-32x32.png

# Personal info
name: Dennis Bautembach
title: PhD Student
email: dennis@bautembach.de

# Social links
#twitter_username: facespics
github_username:  denniskb
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: radulphi
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  At the age of 10 I was gifted [my first PC](images/vtech.jpg) which included a Basic compiler. I've been coding ever since.. Currently I am a PhD student at the University of Crete, expecting to graduate in summer 2021.
  
  **Contents**:
  - [Publications/Projects](#pubs)
  - [Experience](#exp)
  - [Education](#edu)

# Projects Section
projects_title: Publications/Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
#more_title: Misc.
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-paginate
# - jekyll-sitemap 
 
### Sidey ###
 
site: Sidey
url: ""
#title: Sidey
#description: Simple and minimalistic jekyll blogging theme.
#twitter:
#  username: #yourusername
#  card: summary
#  creator: #yourusername
#author:
#  twitter: #yourusername
#  name: #yourusername
#  avatar:
#  email: #youremail
#  url: #yoururl
permalink: pretty

baseurl:

highlighter: rouge
pygments: false

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

#sass:
#  sass_dir:          _sass
#  style:            :compressed

#plugins: # added above
#  - jekyll-paginate
#  - jekyll-seo-tag
#  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "blog/default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
